### ISSUE TITLE
Add support for hex numbers?

### ISSUE THREAD

**Issue by devcarbon-com** [D00mch/DartClojure#18]
Currently anything that has hex formatted numbers will fail to convert.

For example: `0xff0b2d49` => `Can't convert the code: 0xff0b2d49`

**Comment by D00mch** [comment]
Thanks, I will take a look.

**Comment by D00mch** [comment]
https://github.com/D00mch/DartClojure/releases/tag/0.2.15

```bash
$ npm i dartclojure
$ npx dartclojure 'Color(0xFFE3F2FD)'
(m/Color 0xFFE3F2FD)
```
